version: "3.5"
services:
  centos7php72base:
    networks:
      - buildnet
    build:
      context: .
      dockerfile: Dockerfile.el7-base
      network: buildnet
    image: aursu/php72build:7-base
  centos7php72:
    volumes:
      - rpms:/home/centos/rpmbuild/SRPMS
      - rpm7:/home/centos/rpmbuild/RPMS
    build:
      context: .
      dockerfile: Dockerfile.el7
    image: aursu/php72build:el7
  centos7php72rel:
    command: ["-ba", "--with", "relocation"]
    volumes:
      - rpms:/home/centos/rpmbuild/SRPMS
      - rpm7:/home/centos/rpmbuild/RPMS
    build:
      context: .
      dockerfile: Dockerfile.el7
    image: aursu/php72build:el7
  centos7php7my:
    command: ["-ba", "--with", "libmysql"]
    volumes:
      - rpms:/home/centos/rpmbuild/SRPMS
      - rpm7:/home/centos/rpmbuild/RPMS
    build:
      context: .
      dockerfile: Dockerfile.el7
    image: aursu/php72build:el7

volumes:
  rpms:
    name: rpms
  rpm7:
    name: rpm7

networks:
  buildnet:
    external: true
    name: buildnet
