version: "3.5"
services:
  centos6php72base:
    networks:
      - buildnet
    build:
      context: .
      dockerfile: Dockerfile.base
      network: buildnet
    image: aursu/php72build:6-base
  centos6php72ap24base:
    networks:
      - buildnet
    build:
      context: .
      dockerfile: Dockerfile.ap24-base
      network: buildnet
    image: aursu/php72build:6-ap24base
  centos6php72:
    volumes:
      - rpms:/home/centos/rpmbuild/SRPMS
      - rpm6:/home/centos/rpmbuild/RPMS
    build:
      context: .
    image: aursu/php72build:el6
  centos6php72rel:
    command: ["-ba", "--with", "relocation"]
    volumes:
      - rpms:/home/centos/rpmbuild/SRPMS
      - rpm6:/home/centos/rpmbuild/RPMS
    build:
      context: .
    image: aursu/php72build:el6
  centos6php72my:
    command: ["-ba", "--with", "libmysql"]
    volumes:
      - rpms:/home/centos/rpmbuild/SRPMS
      - rpm6:/home/centos/rpmbuild/RPMS
    build:
      context: .
    image: aursu/php72build:el6
  centos6php72ap24:
    volumes:
      - rpms:/home/centos/rpmbuild/SRPMS
      - rpm6:/home/centos/rpmbuild/RPMS
    build:
      context: .
      dockerfile: Dockerfile.ap24
    image: aursu/php72build:6-ap24
  centos6php72ap24rel:
    command: ["-ba", "--with", "relocation"]
    volumes:
      - rpms:/home/centos/rpmbuild/SRPMS
      - rpm6:/home/centos/rpmbuild/RPMS
    build:
      context: .
      dockerfile: Dockerfile.ap24
    image: aursu/php72build:6-ap24
  centos6php7ap24my:
    command: ["-ba", "--with", "libmysql"]
    volumes:
      - rpms:/home/centos/rpmbuild/SRPMS
      - rpm6:/home/centos/rpmbuild/RPMS
    build:
      context: .
    image: aursu/php72build:6-ap24


volumes:
  rpms:
    name: rpms
  rpm6:
    name: rpm6

networks:
  buildnet:
    external: true
    name: buildnet
